version: "2"

services:

  picocms:
    restart: always
    build: .
    image: qnimbus/docker-picocms
    command:
      "/run.sh"
    ports:
      - 80:80
    volumes:
    networks:
      - picocms

networks:
  picocms:
    driver: bridge